"""Tornar secretaria_origem opcional

Revision ID: 2d30719ed097
Revises: fc266107e5ee
Create Date: 2025-12-09 01:22:29.487542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d30719ed097'
down_revision = 'fc266107e5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocolos', schema=None) as batch_op:
        batch_op.alter_column('secretaria_origem_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocolos', schema=None) as batch_op:
        batch_op.alter_column('secretaria_origem_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
