"""Protocolo numero nullable

Revision ID: fc266107e5ee
Revises: ff2069a437ec
Create Date: 2025-12-09 01:14:00.304204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc266107e5ee'
down_revision = 'ff2069a437ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocolos', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocolos', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
