"""Add arquivo field to tramitacao

Revision ID: ff2069a437ec
Revises: 9c5ec709fd7f
Create Date: 2025-12-09 00:35:54.644145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2069a437ec'
down_revision = '9c5ec709fd7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tramitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tramitacoes', schema=None) as batch_op:
        batch_op.drop_column('arquivo')

    # ### end Alembic commands ###
